package schema

// TypeMapping 定义 Go 类型到 SQL 类型的映射表
var TypeMapping = map[string]map[string]string{
	"mysql": {
		"int":       "INT",
		"int8":      "TINYINT",
		"int16":     "SMALLINT",
		"int32":     "INT",
		"int64":     "BIGINT",
		"uint":      "INT UNSIGNED",
		"uint8":     "TINYINT UNSIGNED",
		"uint16":    "SMALLINT UNSIGNED",
		"uint32":    "INT UNSIGNED",
		"uint64":    "BIGINT UNSIGNED",
		"float32":   "FLOAT",
		"float64":   "DOUBLE",
		"string":    "VARCHAR(255)",
		"bool":      "BOOLEAN",
		"time.Time": "DATETIME",
		"[]byte":    "BLOB",
	},
	"postgres": {
		"int":       "INTEGER",
		"int8":      "SMALLINT",
		"int16":     "SMALLINT",
		"int32":     "INTEGER",
		"int64":     "BIGINT",
		"uint":      "BIGINT",
		"uint8":     "SMALLINT",
		"uint16":    "INTEGER",
		"uint32":    "BIGINT",
		"uint64":    "NUMERIC",
		"float32":   "REAL",
		"float64":   "DOUBLE PRECISION",
		"string":    "VARCHAR(255)",
		"bool":      "BOOLEAN",
		"time.Time": "TIMESTAMP",
		"[]byte":    "BYTEA",
	},
	"sqlite": {
		"int":       "INTEGER",
		"int8":      "INTEGER",
		"int16":     "INTEGER",
		"int32":     "INTEGER",
		"int64":     "INTEGER",
		"uint":      "INTEGER",
		"uint8":     "INTEGER",
		"uint16":    "INTEGER",
		"uint32":    "INTEGER",
		"uint64":    "INTEGER",
		"float32":   "REAL",
		"float64":   "REAL",
		"string":    "TEXT",
		"bool":      "BOOLEAN",
		"time.Time": "DATETIME",
		"[]byte":    "BLOB",
	},
}
