package schema

import (
	"reflect"
	"runtime"
	"strings"
)

// HasCustomKeepItem reports whether the given model type overrides KeepItem
// instead of inheriting the promoted method from an embedded base model.
//
// Go generates a wrapper for promoted methods whose source location is
// reported as "<autogenerated>". A type that declares its own KeepItem (via
// value or pointer receiver, or without embedding at all) reports a real
// source file instead. We use that distinction to decide whether KeepItem
// carries custom visibility logic that SQL cannot express.
func HasCustomKeepItem(modelType reflect.Type) bool {
	return hasCustomMethod(modelType, "KeepItem")
}

// HasCustomKeepItemFields reports whether the given model type overrides
// KeepItemFields instead of inheriting the promoted method from an embedded
// base model. It uses the same "<autogenerated>" detection as HasCustomKeepItem.
func HasCustomKeepItemFields(modelType reflect.Type) bool {
	return hasCustomMethod(modelType, "KeepItemFields")
}

// hasCustomMethod reports whether modelType declares its own methodName instead
// of inheriting a promoted (autogenerated) wrapper from an embedded base.
func hasCustomMethod(modelType reflect.Type, methodName string) bool {
	if modelType == nil {
		return false
	}
	if modelType.Kind() == reflect.Ptr {
		modelType = modelType.Elem()
	}

	// Probe the value method set first; fall back to the pointer method set
	// for pointer-receiver overrides that are not promoted to the value set.
	if isCustom, found := methodIsCustom(modelType, methodName); found {
		if isCustom {
			return true
		}
		// Value set says promoted; double-check the pointer set in case an
		// override only exists there.
		if isCustomPtr, foundPtr := methodIsCustom(reflect.PointerTo(modelType), methodName); foundPtr {
			return isCustomPtr
		}
		return false
	}
	if isCustom, found := methodIsCustom(reflect.PointerTo(modelType), methodName); found {
		return isCustom
	}
	return false
}

// methodIsCustom inspects methodName on rt, returning whether it is a custom
// (non-promoted) declaration and whether the method exists at all.
func methodIsCustom(rt reflect.Type, methodName string) (isCustom bool, found bool) {
	m, ok := rt.MethodByName(methodName)
	if !ok {
		return false, false
	}
	pc := m.Func.Pointer()
	file, _ := runtime.FuncForPC(pc).FileLine(pc)
	return !strings.Contains(file, "<autogenerated>"), true
}
